services:
    droppy_webapp.make_event.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [make_event_type, "make_event_form"]
    droppy_webapp.make_event.form.type:
        class: Droppy\WebApplicationBundle\Form\Type\MakeEventFormType
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: make_event_type }
    droppy_webapp.make_event_include.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [make_event_include_type, "make_event_include_form"]
    droppy_webapp.make_event_include.form.type:
        class: Droppy\WebApplicationBundle\Form\Type\MakeEventIncludeFormType
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: make_event_include_type }
    droppy_webapp.make_event.form.handler:
        class: Droppy\WebApplicationBundle\Form\Handler\MakeEventFormHandler
        arguments: [@droppy_webapp.make_event.form, @request, @droppy_user_manager, @droppy_webapp.icon_uploader]
        scope: request
