services:
    droppy_webapp.schedule_creation.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [schedule_creation_type, "schedule_creation_form"]
    droppy_webapp.schedule_creation.form.type:
        class: Droppy\WebApplicationBundle\Form\Type\ScheduleCreationFormType
        tags:
            - { name: form.type, alias: schedule_creation_type }
    droppy_webapp.schedule_creation.form.handler:
        class: Droppy\WebApplicationBundle\Form\Handler\ScheduleCreationFormHandler
        arguments: [@droppy_webapp.schedule_creation.form, @request, @droppy_user_manager, @droppy_webapp.icon_uploader]
        scope: request
    droppy_webapp.schedule_creation.creator_visible_selector:
        class: Droppy\WebApplicationBundle\Form\Type\CreatorVisibilityFormType
        tags:
            - { name: form.type, alias: creator_visible_selector }