#DroppyUserBundle:
#   resource: "@DroppyUserBundle/Resources/config/routing.yml"
#    prefix:   /droppy
    

DroppyWebApplicationBundle:
    resource: "@DroppyWebApplicationBundle/Resources/config/routing.yml"
    prefix:   /droppy

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
