security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_user_bundle:
            id: fos_user.user_manager
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
 #           pattern:  ^/droppy/(top|login$|register|resetting)
  #          anonymous: true

        main:
            pattern:    ^/droppy
            form_login:
                provider: fos_user_bundle
                login_path: /droppy/top
                check_path: /droppy/login_check
                default_target_path: /droppy/
                failure_path: /droppy/login
                remember_me: true
            remember_me:
                key: %secret%
            logout:
                path: /droppy/logout
                target: /droppy/top
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/droppy/(top|login$|register|resetting), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/droppy, roles: ROLE_USER }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
