droppy_webapp_schedule_create:
    pattern: /create
    defaults: { _controller: DroppyWebApplicationBundle:ScheduleCreation:createSchedule }

droppy_schedule_drop:
    pattern: /drop
    defaults: { _controller: DroppyWebApplicationBundle:ScheduleDrop:dropSchedule }

droppy_schedule_undrop:
    pattern: /undrop
    defaults: { _controller: DroppyWebApplicationBundle:ScheduleDrop:undropSchedule }

droppy_schedule_get_main_schedule:
    pattern: /getmainschedule/{date}
    defaults: { _controller: DroppyWebApplicationBundle:Default:getMainSchedule, date: now }
    requirements:
        date: \d{4}-\d{2}