parameters:
#    droppy_user.example.class: Droppy\UserBundle\Example

services:
    droppy_user.registration.form.type:
        class: Droppy\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: droppy_user_registration }
            
    droppy_user.registration.form.handler:
        class: Droppy\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false

    droppy_user_manager:
        class: Droppy\UserBundle\Entity\UserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %fos_user.model.user.class%]
        public: true 
        
    droppy_user.listener.schedule_creator:
        class: Droppy\UserBundle\Listener\ScheduleCreator
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }


